export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
export const GET_SEVEN_DAYS_WEATHER = "GET_SEVEN_DAYS_WEATHER";
export const GET_ARRAY = "GET_ARRAY";
export const GET_FIRST_LAST_DAY = "GET_FIRST_LAST_DAY";